AntiGlitcher:
  enabled: true
  taskeveryseconds: 30
  antiglitchdurationseconds: 60
SignBackup:
  enabled: true
  taskeveryseconds: 300
SignFormat:
- '&7[&aRandomTP&7]'
- '&2Blöcke: %distance%'
- '&cPreis: %price%'
- '&a(Hier klicken)'
Inventory:
  Rows: 1
  MenuName: '&nRandom Teleport'
  Items:
    '0':
      id: '268'
      slot: 0
      name: '&8◆ &7&nBasic Teleport&r &8◆'
      cost: 5
      distance: 100
      world: world
      cooldown: 600
      permission: randomtp.use.user
      lore:
      - '&r'
      - '&8◆ &eTeleport Entfernung: %distance% blöcke'
      - '&8◆ &ePreis: 10 ⛃'
      - '&6Klicke zum Teleportieren'
    '1':
      id: '272'
      slot: 1
      name: '&8◆ &a&nAdvanced Teleport&r &8◆'
      cost: 10
      distance: 250
      world: world
      cooldown: 600
      permission: randomtp.use.user
      lore:
      - '&r'
      - '&8◆ &eTeleport Entfernung: %distance% blöcke'
      - '&8◆ &ePreis: 20 ⛃'
      - '&6Klicke zum Teleportieren'
    '2':
      id: '267'
      slot: 2
      name: '&8◆ &e&nExtreme Teleport&r &8◆'
      cost: 0
      distance: 1000
      world: world
      cooldown: 86400
      permission: randomtp.use.vip
      lore:
      - '&r'
      - '&8◆ &eTeleport Entfernung: %distance% blöcke'
      - '&8◆ &ePreis: %cost% ⛃'
      - '&6Klicke zum Teleportieren'
      - '&r'
      - '&cNur für Premiumm.'
