## BYTE Disease config File

## Welcome to the RPG plugin designed for www.byte.org.uk be careful how you edit the following details use a yaml editor if you do have to edit this file.


################## Bar and scoreboards ###################

##Use the BYTE scoreboard
byteScoreboardEnabled: false

##use scoreboard stats for Disease levels
useScoreboardStats: false

##use worldguard cure regions
useWorldGuard: true

##use actionabar for messages
actionBarEnabled: true

################## world settings #########################

##Enabled worlds
worlds:
  - world
  - world_nether
  - world_the_end

################## Disease check settings #################

##Time in ticks between each disease check
timeBetweenChecks: 500


################## Disease levels ################

##levels at which messages sent in %

##temperature levels at which stuff happens
hypothermic: -80
chilled: -60
cold: -40
warm: 40
hot: 60
fever: 80


##Sickness levels at which events happen
unwell: 40
queasy: 60
sick: 80



################ Disease Infection chance ################

##change this for odds, 10 is 1 in 10 chance, 100 is 1 in 100 chance - best keep even numbers for fleshwound modifier


swampFeverChance: 36
yellowFeverChance: 100
choleraChance: 100
poxChance: 100
plagueChance: 100
pneumoniaChance: 100
whoopingCoughChance: 100
openWoundChance: 100
rabiesChance: 100
arrowWoundChance: 150

##chance of cutting your hand punching blocks with no tool
fleshWoundChance: 15
##chance of breaking your leg on fall
brokenLegChance: 15

################ Disease Cure  chances ################

##amount the temp cure potion redcues temperature and sickness by and the chance it cures the disease if you reach 0
tempCureReduction: 35
tempCureChance: 10

##chance of removing arrow from wound percent
arrowWoundCureChance: 70

##use doctor sign cost
doctorFee: 100

##fine in money for dying with disease
deathFine: 0

##hospital based recovery values 
tempHospitalReduce: 10
sickHospitalReduce: 10

################ Immunity Settings  ################

##decrease of immunity per infection
immunityDecreaseOnInfection: 5

##increase of immunity for a disease upon cure
immunityGainOnHeal: 15

##immunity increase on vaccine
vaccineImmunityIncrease: 10

##immunity decrease on death
immunityDecreaseOnDeath: 20


################ Disease effects  ################

##drop item in had on coughinh fit 
dropItemOnCough: true

##cure after player death
cureOnDeath: true

################ Choking Foods ########################

##chance of choking 
chokeChance: 250

##list the foods that have a chance of choking you 
chokeItems:
  - 260
  - 297
  - 319
  - 320
  - 349
  - 350
  - 358
  - 363
  - 364
  - 365
  - 366
  - 367
  - 391
  - 392
  - 393
  - 411
  - 412
  - 423
  - 424

################ TEMPERATURE SYSTEM ########################

##use temperature system
useTemp: true

##cold levels in player ambient temp - temp change increas per level
freezingAmbient: 5
coldAmbient: 1
hotAmbient: 25
boilingAmbient: 30

##temperature adjsuting values
##adjusting cold values if in cold area
coldTempLower: 4
FreezingTempLower: 7
normalTempRise: 3

##adjusting hot values if in hot area
hotTempRise: 4
boilingTempRise: 7
normalTempLower: 3

##temp added if sprinting when checked
sprintTempRise: 2

############### TEMPERATURE VARIABLES ######################

##Radius heat sources effect players
heatRadius: 3

##Heat generated by heat sources in area

fireHeat: 10
torchHeat: 2
lavaHeat: 1
jackolanternHeat: 1
redstoneTorchHeat: 2

torchHeatHeld: 2
redstoneTorchHeatHeld: 1
lavaBucketHeatHeld: 5
jackolanternHeatHeld: 1




