Settings:
  Prefix: '&bAuktionen > ' #Prefix of when you get Crazy Auctions Messages.
  GUIName: '&nAuktionen' #Name of the Main GUI.
  Players-Current-Items: '&eDeine Listungen' #The Name of the Player Current Items GUI.
  Cancelled/Expired-Items: '&cBeendete/Abgelaufene Listungen' #Name of the Cancelled/Expired GUI.
  Buying-Item: '&aBestätigen' #Name of the Buying GUI.
  Bidding-On-Item: '&8> Du bietest auf dieses Item.' #Name of the Bidding GUI.
  Categories: '&nKategorien' #Name of the Category GUI.
  Sell-Time: 7d #The time that each item will sell for.
  Bid-Time: 2m 30s #Time for each item that is biddable.
  Full-Expire-Time: 30d #The full time the item is in the crazy auctions.
  Bid-Winner-Time: 20d #The time the winner of a bid has to claim there prize.
  Minimum-Sell-Price: 1 #Minimum amount you can sell a item for.
  Max-Beginning-Sell-Price: 100000000 #Max amount you can sell a item for.
  Minimum-Bid-Price: 10 #Minimum starting bid.
  Max-Beginning-Bid-Price: 1000000 #Maximum starting bid.
  Allow-Damaged-Items: True #Allow items that have been damaged.
  Category-Page-Opens-First: False #If set to true the categories page will open when they do /CA.
  Sounds:
    Toggle: False #Disable the clicking sound.
    Sound: 'CLICK' #Make sure if you use 1.8 or lower you use the 1.8 sound and 1.9 and up use 1.9 sounds. The default sound is 1.8.
    #1.8 sounds are found here: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
    #1.9 sounds are found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  GUISettings: #Settings for things in the gui. ◆
    SellingItemLore: #The lore on items that are being sold.
      - '&7&m+------------------------------+'
      - '&aKlicke um das Item zu kaufen.'
      - ''
      - '&e◆ Preis: &7%Price% ⛃'
      - '&e◆ Verkäufer: &7%Seller%'
      - '&7&m+------------------------------+'
    CurrentLore: #Lore on items that are in your current items GUI.
      - '&7&m+------------------------------+'
      - '&cKlicke um abzubrechen.'
      - ''
      - '&e◆ Preis: &7%Price% ⛃'
      - '&e◆ Läuft ab in: &7%Time%'
      - '&7&m+------------------------------+'
    Cancelled/ExpiredLore: #Lore on items that are in your cancelled/expired GUI.
      - '&7&m+------------------------------+'
      - '&eKlicke um das Item zu erhalten.'
      - ''
      - '&e◆ Abgelaufen: &7%Time%'
      - '&7&m+------------------------------+'
    Bidding: #Lore on Bidding Items.
      - '&7&m+------------------------------+'
      - '&aKlicke um auf das Item zu bieten.'
      - ''
      - '&e◆ Verkäufer: &7%Seller%'
      - '&e◆ Aktuelles Gebot: &7%TopBid% ⛃'
      - '&e◆ Top Gebot: &7%TopBidder%'
      - '&e◆ Verbleibende Zeit: &7%Time%'
      - '&7&m+------------------------------+'
    Category-Settings:
      Armor:
        Item: '311'
        Toggle: true
        Slot: 20
        Name: '&e&nArmor&r'
        Lore:
          - '&7This category contains all the'
          - '&7armor that are currently being sold.'
      Weapons:
        Item: '276'
        Toggle: true
        Slot: 21
        Name: '&e&nWaffen&r'
        Lore:
          - '&7This category contains all the'
          - '&7weapons that are currently being sold.'
      Tools:
        Item: '278'
        Toggle: true
        Slot: 22
        Name: '&e&nWerkzeug&r'
        Lore:
          - '&7This category contains all the'
          - '&7tools that are currently being sold.'
      Food:
        Item: '364'
        Toggle: true
        Slot: 23
        Name: '&e&nEssen&r'
        Lore:
          - '&7This category contains all the'
          - '&7food that are currently being sold.'
      Potions:
        Item: '373:8227'
        Toggle: true
        Slot: 24
        Name: '&e&nTränke&r'
        Lore:
          - '&7This category contains all the'
          - '&7potions that are currently being sold.'
      Blocks:
        Item: '1'
        Toggle: true
        Slot: 25
        Name: '&e&nBlöcke&r'
        Lore:
          - '&7This category contains all the'
          - '&7blocks that are currently being sold.'
      Other:
        Item: '288'
        Toggle: true
        Slot: 26
        Name: '&e&nAnderes&r'
        Lore:
          - '&7This category contains all the'
          - '&7other items that are currently'
          - '&7being sold.'
      None:
        Item: '166'
        Toggle: true
        Slot: 32
        Name: '&c&nAlles&r'
        Lore:
          - '&7Do not filter the items being sold'
          - '&7into categories.'
    OtherSettings: #Other Settings for the GUIs.
      SellingItems: #The button for your current items.
        Item: '264' #The item that this button is.
        Toggle: true #If the item is in the gui or not.
        Slot: 46 #The slot it is in. I recommend not changing these. If you do make sure they are still in the bottom row.
        Name: '&eItems zum Verkauf' #Name of the item.
        Lore: #Lore of the item.
          - '&7Klicke um die Items zu sehen die du verkaufst.'
      Cancelled/ExpiredItems: #The button for Cancelled/Expired Items.
        Item: '380'
        Toggle: true
        Slot: 47
        Name: '&cAbgelaufene/Beente Items'
        Lore:
          - '&7Click to view the expired items or'
          - '&7cancelled items that you were selling.'
      PreviousPage: #The button for Previous Page.
        Item: '339'
        Toggle: true
        Slot: 49
        Name: '&e&l<<<'
        Lore:
          - '&7Click to view the previous page.'
      Refesh: #The button for Refresh Page.
        Item: '175'
        Toggle: true
        Slot: 50
        Name: '&aAktualisieren'
        Lore:
          - '&7Click to refresh the page.'
      NextPage: #The button for Next Page.
        Item: '339'
        Toggle: true
        Slot: 51
        Name: '&e&l>>>'
        Lore:
          - '&7Click to view the next page.'
      Category1: #The button for Next Page.
        Item: '54'
        Toggle: true
        Slot: 52
        Name: '&6Kategorien'
        Lore:
          - '&eCurrently viewing: &7%Category%'
          - ''
          - '&7Want to see items in specific categories?'
          - '&7Click to see all the categories.'
      Category2: #The button for Next Page.
        Item: '54'
        Toggle: true
        Slot: 48
        Name: '&66Kategorien'
        Lore:
          - '&eCurrently viewing: &7%Category%'
          - ''
          - '&7Want to see items in specific categories?'
          - '&7Click to see all the categories.'
      Bidding/Selling: #Switch between Bidding and Selling.
        Selling:
          Item: '341'
          Toggle: true
          Slot: 53
          Name: '&bVerkäufe'
          Lore:
            - '&7Click to see auctions for items.'
        Bidding:
          Item: '378'
          Toggle: true
          Slot: 53
          Name: '&3Auktionen'
          Lore:
            - '&7Click to see items for sale.'
      WhatIsThis: #The info on all the Books buttons.
        SellingShop: #The Book in the main shop.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&2Informationen'
          Lore:
            - '&7This is where you can sell items'
            - '&7for other players to purchase.'
        BiddingShop: #The Book in the main shop.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Was ist diese Seite?'
          Lore:
            - '&7This is where you can auction items'
            - '&7for other players to bid on.'
        CurrentItems: #The Book in the Current items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Was ist diese Seite??'
          Lore:
            - '&aThese are your current listings, all of'
            - '&athe items you currenty have listed on'
            - '&acrazy auctions are displayed here.'
            - ''
            - '&aYou can cancel and view your listings'
            - '&aexpire time here.'
        Cancelled/ExpiredItems: #The Book in the Cancelled/Expired Items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Was ist diese Seite?'
          Lore:
            - '&aThis page houses all of your cancelled and'
            - '&aexpired items, when a listings is cancelled'
            - '&aor expires you will be able to return that'
            - '&aitem back to you from this menu.'
            - ''
            - '&aJust click on the item and if you have enough'
            - '&ainventory space you will receive that item.'
        Viewing: #The Book in the Viewing Items GUI.
          Item: '340'
          Toggle: true
          Slot: 50
          Name: '&6Was ist diese Seite?'
          Lore:
            - '&aThis page shows all the items that'
            - '&aa player has currently on the bidding'
            - '&aand selling market. You can quickly see'
            - '&awhat a specific player is selling.'
        Categories: #The Book in the Viewing Items GUI.
          Item: '340'
          Toggle: true
          Slot: 54
          Name: '&6Was ist diese Seite?'
          Lore:
            - '&aThis page shows all the categories'
            - '&athat you can choose from. When you click'
            - '&aa category it will open the gui with only'
            - '&aitems that belong to that category.'
      Back: #The Back Buttons.
        Item: '339'
        Slot: 46
        Name: '&6Zurück'
      Return: #The Return Buttons.
        Item: '390'
        Slot: 50
        Name: '&6Komplett Zurück'
        Lore:
          - '&aKlicke um alle beendeten zurückzukehren'
          - '&aund abgelaufene Items.'
      Confirm: #The Confirm Buttons.
        Item: '160:5'
        Name: '&aBestätigen'
      Cancel: #The Cancel Buttons.
        Item: '160:14'
        Name: '&cAbbrechen'
      Your-Item: #The item that shows when you try to buy/bid on your item.
        Item: '166'
        Name: '&cDu kannst nicht dein eigenes Item kaufen.'
      Cant-Afford: #The item that shows when you cant afford this item.
        Item: '166'
        Name: '&cDu kannst dir dieses Item nicht leisten.'
      Top-Bidder: #The item for when a player is already the top bidder.
        Item: '166'
        Name: '&cDu bist schon der Top Bietende.'
      Bidding: #The item in the middle when bidding on an item.
        Item: '160:15'
        Name: '&7Bieten'
        Lore:
          - '&7<--&aHinzufügen &cEntfernen&7-->'
          - '&9Dein momentanes Gebot: &e$%Bid%'
          - '&9Dein momentanes Tob Gebot: &e$%TopBid%'
      Bid: #The button for when you want to confirm your bid.
        Item: '160:3'
        Name: '&bJetzt bieten'
        Lore:
          - '&7Klicke um jetzt zu bieten.'
  BlackList:
    - '7'
    - '120'