# Like this plugin? Check out TitleMotdAdvanced
# The advanced version of this plugin with 400+ placholders and animations
# @ http://www.mvdw-software.be/

# Message on first join
firstjoin:
  # Broadcast the message to all players
  broadcast: false
  # Title message
  title: '&8◆ &6&l&nGameNetz24-Survival&r &8◆'
  # Subtitle message
  subtitle: '&eWillkommen auf deinem Survival Server!'
  # Fade in time in TICKS (20 ticks = 1 sec)
  fadein: 25
  # Stay on screen time in TICKS
  staytime: 60
  # Fade out time in TICKS
  fadeout: 25

# Message on rejoin
rejoin:
  # Broadcast the message to all players
  broadcast: false
  # Title message
  title: '&8◆ &6&l&nGameNetz24-Survival&r &8◆'
  # Subtitle message
  subtitle: '&eWillkommen zurück!!'
  # Fade in time in TICKS (20 ticks = 1 sec)
  fadein: 25
  # Stay on screen time in TICKS
  staytime: 60
  # Fade out time in TICKS
  fadeout: 25

